package com.seproject.backend.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import com.seproject.backend.entity.Project;

/**
 * Teamspace Entity
 * 
 * Represents a teamspace within a project where team members can collaborate.
 * Each teamspace belongs to a project and has a creator.
 */
@Data
@Entity
@Table(name = "teamspaces")
@NoArgsConstructor
@AllArgsConstructor
public class Teamspace {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String description;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    @Column(name = "creator_id", nullable = false)
    private Long creatorId;

    // Getters and setters are automatically generated by Lombok @Data annotation
} 